Update dynamo.yml

diff --git a/.github/workflows/dynamo.yml b/.github/workflows/dynamo.yml
--- a/.github/workflows/dynamo.yml
+++ b/.github/workflows/dynamo.yml
@@ -21,7 +21,7 @@ concurrency:
 
 jobs:
   generate-matrix:
-    name: "Generate 💿️ Matrix"
+    name: "💿️ Matrix"
     runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
@@ -63,6 +63,7 @@ jobs:
           #./quickget --check ${{ matrix.file }} | tee results/${{ matrix.file }}.txt
           chmod a+x action
           ./action ${{ matrix.file }} | tee results/${{ matrix.file }}.txt
+          sort -u < TODO/all | tee TODO/all
           #if grep -vqE '^(PASS:|SKIP:)' results/${{ matrix.file }}.txt; then
             #grep -vE '^(PASS:|SKIP:)' results/${{ matrix.file }}.txt >> $GITHUB_STEP_SUMMARY
             #exit 1
@@ -76,7 +77,7 @@ jobs:
           path: results/${{ matrix.file }}.txt
 
   end:
-    name: "Finish 🏁"
+    name: "🏁 Finish"
     needs: run-actions
     if: always()
     runs-on: ubuntu-latest
@@ -90,11 +91,21 @@ jobs:
           path: results
           merge-multiple: true
 
-      - name: "Display results 📊"
+      - name: "Display and push results 📊"
         run: |
           for file in results/*.txt; do
             cat "$file" >> result
           done
+          sort -u < TODO/all | tee TODO/all
+          git config --global user.name "web-flow"
+          git config --global user.email "noreply@github.com"
+          git status
+          git add . || echo "add . failed"
+          git add TODO/all || echo "add TODO/all failed"
+          git add --all || echo "add --all failed"
+          git commit -m "update supported" || echo "commit failed"
+          git push || echo "push failed"
+          git status
           #PASSED=$(grep -c '^PASS:' result | wc -l)
           #FAILED=$(grep -c '^FAIL:' result | wc -l 2>/dev/null | echo '0')
           #SKIPPED=$(grep -c '^SKIP:' result | wc -l)
